#ifndef HRC_INTERFACE_GLOBAL_H
#define HRC_INTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HRC_INTERFACE_LIBRARY)
#  define HRC_INTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define HRC_INTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HRC_INTERFACE_GLOBAL_H
